#!/usr/bin/env node
/**
 * Counts lines of hand-written source.
 *
 * Files come from git's index plus untracked-but-not-ignored files, so anything
 * gitignored — node_modules, .next, out, coverage, build output — is excluded
 * for free, while work in progress still counts. On top of that we drop
 * files that are checked in but generated or not source at all: the lockfile,
 * Drizzle's migrations and snapshots, static assets in public/, and the icon.
 *
 *   node scripts/count-lines.mjs           # summary + top 5
 *   node scripts/count-lines.mjs --top 20  # summary + top 20
 *   node scripts/count-lines.mjs --all     # every file, largest first
 *   node scripts/count-lines.mjs --json    # machine-readable
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, statSync } from 'node:fs';
import { extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** Extensions we consider source. */
const SOURCE_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.css',
  '.scss',
  '.sql',
  '.json',
  '.md',
]);

/** Checked in, but not hand-written source. */
const EXCLUDED_PATHS = [
  /^package-lock\.json$/,
  /^drizzle\//, // generated by drizzle-kit: migrations and snapshots
  /^public\//, // static assets
  /^\.agents\//, // vendored third-party agent skills
  /(^|\/)next-env\.d\.ts$/,
  /(^|\/)skills-lock\.json$/,
];

/** Counted, but reported separately from application code. */
const NON_CODE_EXTENSIONS = new Set(['.json', '.md']);

/** Tests are source, but they are reported on their own line: growing them is good. */
const TEST_PATH = /(^|\/)tests?\//;

function trackedFiles() {
  try {
    const out = execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], {
      cwd: ROOT,
      encoding: 'utf8',
    });
    return [...new Set(out.split('\0').filter(Boolean))];
  } catch {
    console.error('Not a git repository (or git is unavailable), so there is no file list to read.');
    process.exit(1);
  }
}

function isSource(path) {
  if (!SOURCE_EXTENSIONS.has(extname(path))) return false;
  return !EXCLUDED_PATHS.some((pattern) => pattern.test(path));
}

function countLines(path) {
  const absolute = join(ROOT, path);
  try {
    if (!statSync(absolute).isFile()) return null;
    const text = readFileSync(absolute, 'utf8');
    if (!text) return 0;
    // A trailing newline terminates the last line rather than starting a new one.
    return text.endsWith('\n') ? text.split('\n').length - 1 : text.split('\n').length;
  } catch {
    return null; // deleted from the working tree but still in the index
  }
}

function group(files, keyOf) {
  const totals = new Map();
  for (const file of files) {
    const key = keyOf(file);
    const current = totals.get(key) ?? { files: 0, lines: 0 };
    totals.set(key, { files: current.files + 1, lines: current.lines + file.lines });
  }
  return [...totals.entries()].sort((a, b) => b[1].lines - a[1].lines);
}

function table(rows, headers) {
  const widths = headers.map((header, index) =>
    Math.max(header.length, ...rows.map((row) => String(row[index]).length))
  );
  const line = (cells) =>
    cells
      .map((cell, index) => (index === 0 ? String(cell).padEnd(widths[index]) : String(cell).padStart(widths[index])))
      .join('  ');
  console.log(line(headers));
  console.log(widths.map((width) => '─'.repeat(width)).join('  '));
  for (const row of rows) console.log(line(row));
}

// ---------------------------------------------------------------- main

const args = process.argv.slice(2);
const asJson = args.includes('--json');
const showAll = args.includes('--all');
const topIndex = args.indexOf('--top');
const topCount = showAll ? Infinity : topIndex === -1 ? 5 : Number(args[topIndex + 1]) || 5;

const files = trackedFiles()
  .filter(isSource)
  .map((path) => ({ path, lines: countLines(path), ext: extname(path) }))
  .filter((file) => file.lines !== null)
  .sort((a, b) => b.lines - a.lines);

const source = files.filter((file) => !NON_CODE_EXTENSIONS.has(file.ext));
const code = source.filter((file) => !TEST_PATH.test(file.path));
const tests = source.filter((file) => TEST_PATH.test(file.path));
const other = files.filter((file) => NON_CODE_EXTENSIONS.has(file.ext));
const sum = (list) => list.reduce((total, file) => total + file.lines, 0);

if (asJson) {
  console.log(
    JSON.stringify(
      {
        totals: { code: sum(code), tests: sum(tests), docsAndConfig: sum(other), files: code.length },
        byExtension: Object.fromEntries(group(code, (file) => file.ext)),
        files: (showAll ? code : code.slice(0, topCount)).map(({ path, lines }) => ({ path, lines })),
      },
      null,
      2
    )
  );
  process.exit(0);
}

console.log(`\nCode  ${sum(code).toLocaleString()} lines across ${code.length} files\n`);
table(
  group(code, (file) => file.ext).map(([ext, totals]) => [ext, totals.files, totals.lines.toLocaleString()]),
  ['ext', 'files', 'lines']
);

console.log(`\nLargest ${Math.min(topCount, code.length)} files\n`);
table(
  code.slice(0, topCount).map((file, index) => [`${index + 1}. ${file.path}`, file.lines.toLocaleString()]),
  ['file', 'lines']
);

if (tests.length) {
  console.log(`\nTests  ${sum(tests).toLocaleString()} lines across ${tests.length} files\n`);
  table(
    tests.map((file) => [file.path, file.lines.toLocaleString()]),
    ['file', 'lines']
  );
}

if (other.length) {
  console.log(`\nDocs and config (excluded from the code total)  ${sum(other).toLocaleString()} lines\n`);
  table(
    group(other, (file) => file.ext).map(([ext, totals]) => [ext, totals.files, totals.lines.toLocaleString()]),
    ['ext', 'files', 'lines']
  );
}

console.log('');
